# Adapted from: https://github.com/jdblischak/smk-simple-slurm/

cluster:
  mkdir -p slurm-logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.runtime}
    --job-name=smk-{rule}-{wildcards}
    --output=slurm-logs/{rule}/%j.out
    --parsable
    --no-requeue
cluster-status: "slurm_status.py"
default-resources:
  - partition=wjg,sfgf,biochem,owners
  - mem_mb=8000
  - runtime=60 # 1 hour
restart-times: 3 # This is good for robustness, but bad for debugging
max-jobs-per-second: 2
max-status-checks-per-second: 1
local-cores: 1
# latency-wait: 10 # Enable if there's routinely files that are missed due to filesystem latency
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
